<div class="main family-search">
    <h1>Add Family Member</h1>
    <em class="alt">
    	Find the individual you'd like to add by name
    </em>
    <div class="section-body">Please enter the full korean name or the first name in English.</div>
    <input type="text" name="q_name" /> <span class="button" id="search">search</span>
    <div id="search_result"></div>
</div>
<div class="CTA">
    <button class="green-button first" id="add-family-member"><span>add member</span></button>
    <button class="black-button close"><span>cancel</span></button>
</div>

