<div class="main">
    <h1>Member Registration</h1>
    <em class="alt error">* required</em>
    <p class="error"></p>
    <div class="new-member">
    
        <div class="section-title">기본정보</div>
        <table>
            <tr>
                <td width="80" align="center"><span class="error">*&nbsp;</span>한글 이름</td>
	            <td width="200"><input name="name" type="text" id="name" /></td>
	            <td width="80" align="center">Email</td>
	            <td width="200">
	            	<input name="email" type="text" />
	            </td>
	            <td width="80" align="center">성별</td>
	            <td>
	                <input type="radio" name="gender" value="M" checked="checked" id="men" /><label for="men">남</label>
	                <input type="radio" name="gender" value="F" id="women" /><label for="women">여</label>
	            </td>
            </tr>
            <tr>
	            <td align="center">Last Name</td>
	            <td><input name="e_last" type="text" /></td>
	            <td align="center">First Name</td>
	            <td><input name="e_first" type="text" /></td>
	            <td align="center">Mid. Name</td>
	            <td><input class="mid" name="e_middle" type="text" /></td>
            </tr>
            <tr>
	            <td align="center"><span class="error">*&nbsp;</span>생년월일</td>
	            <td colspan="3">
	            	<select name="birth_month" class="month">
	            		<option value="0">month</option>
		            	<?php 
		            		foreach (range(1, 12) as $month) {
		            			echo '<option value="' . $month . '">' . $month . '</option>';
		            		}
		            	?>
	            	</select> /
	            	<select name="birth_day" class="day">
	            		<option value="0">day</option>
		            	<?php 
		            		foreach (range(1, 31) as $day) {
		            			echo '<option value="' . $day . '">' . $day . '</option>';
		            		}
		            	?>
	            	</select> /
	            	<select name="birth_year" class="year">
	            		<option value="0">year</option>
		            	<?php
		            		$thisYear = date('Y');
		            		$startYear = ($thisYear - 110);
		            		$selectYear = ($thisYear);
		            		foreach (range($thisYear, $startYear) as $year) {
		            			echo '<option value="' . $year . '">' . $year . '</option>';
		            		}
		            	?>
	            	</select>&nbsp;&nbsp;
	            	<input type="radio" name="birth_lunar" value="0" checked="checked" id="sun" /><label for="sun">양력</label>
	                <input type="radio" name="birth_lunar" value="1" id="lunar" /><label for="lunar">음력</label>
	            </td>
	            <td align="center">교회 직분</td>
	            <td>
	                <select name="duty">
	                    <option value="0">--</option>          
	                	<?php echo $this->dutyOptions; ?>
	                </select>
	            </td>	            
            </tr>
            <tr>
	            <td align="center">집전화 #</td>
	            <td><input name="home_phone" type="text"></td>
	            <td align="center">모바일 #</td>
	            <td><input name="mobile_phone" type="text"></td>	            
	            <td align="center">상태</td>
	            <td>
	            	<input type="radio" name="active" value="1" id="active" checked="checked" /><label for="active">활성</label>
	                <input type="radio" name="active" value="0" id="inactive" /><label for="inactive">비활성</label>
	            </td>
            </tr>
            <tr>
            	<td align="center">비지니스 #</td>
	            <td>
	                <input type="text" name="business_phone" />
	            </td>
	            <td align="center">교회 등록일</td>
	            <td>
	            	<input type="text" class="mid" name="registered_on" /> (yyyy-mm-dd)
	            </td>
	            <td align="center">결혼</td>
	            <td>
	                <select name="marital_status">  
	                	<?php echo $this->maritalOptions; ?>
	                </select>
	            </td>
            </tr>
            <tr>
            	<td align="center">세례</td>
	            <td colspan="5">
	                <input type="radio" name="baptized" value="1" id="baped" /><label for="baped">받음</label>
	                <input type="radio" name="baptized" value="0" checked="checked" id="nobaped" /><label for="nobaped">안받음</label>
	                <span class="baptized_on hide">세례일: <input type="text" class="mid" name="baptized_on" /> (yyyy-mm-dd)</span>	                
	            </td>
            </tr> 
            <tr>
	            <td align="center"><span class="error">*&nbsp;</span>주소</td>
	            <td colspan="5" valign="top">
	            	<table class="address">
	            		<tr>
				            <td align="right">Street</td>
				            <td colspan="5"><input class="street" name="street" type="text" /></td>
				        </tr>
				        <tr>
	                		<td align="right">City</td>
	                		<td><input name="city" type="text" /></td>
	                		<td align="right">State</td>
	                		<td>                   
				                <select name="state" class="state">
				                <?php echo $this->stateOptions; ?>    
				                </select>
				            </td>
	                		<td align="right">Zip</td>
	                		<td><input class="zip" name="zip" type="text" maxlength="5"></td>
	                	</tr>
	                </table>
	            </td>
            </tr>
        </table>
        
        <div class="section-title">가족정보 <span class="button" id="add-member">Add Family Member</span></div>
        <table id="family-member">
            <tr>
                <td align="center" width="80"><span class="error">*&nbsp;</span>한글 이름</td>
                <td align="center" width="80">Last Name</td>
                <td align="center" width="80">First Name</td>
                <td align="center" width="80">성별</td>
                <td align="center" width="60">관계</td>
                <td align="center" width="170"><span class="error">*&nbsp;</span>생년월일</td>
                <td align="center" width="80">모바일 #</td>
                <td align="center">Email</td>
            </tr>
        </table>      
    </div>    
</div>
<div class="CTA">
    <button class="green-button submit first" id="new-member"><span>submit</span></button>   
</div>

