<div class="back-button-container">
    <button onclick="location.href='/disciples'" class="black-button"><span>back</span></button>
</div>
<div class="inner-right">
    <h1>Under Construction!!</h1>
    <p class="error">This will be the page for showing various statistic reports such as statistic by age, by location, by gender, or by register status.</p>      
    <p class="error">이 페이지는 여러가지 통계자료를 보여주는 페이지로서, 통계 옵션은 나이, 지역, 성별, 등록여부를 포함하게 됩니다.</p>
</div>