<div class="inner-right">
    <h1>REGISTER A NEW USER</h1>
    
    <?php echo $this->errorMessage; ?>

    <form name="register" method="POST" action="">
        <fieldset>
            <dl class="<?php echo $this->formError['username'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="login" type="text" name="username" value="<?php echo $this->username; ?>" />
                    <label class="pseudo-label">Username</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid Username</span>
                </dd>
            </dl>
            <dl class="<?php echo $this->formError['email'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="login" type="text" name="email" value="<?php echo $this->email; ?>" />
                    <label class="pseudo-label">Email Address</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid Email Address</span>
                </dd>
            </dl>
            <dl class="<?php echo $this->formError['firstName'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="login" type="text" name="firstName" value="<?php echo $this->firstName; ?>" />
                    <label class="pseudo-label">First Name</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid First Name</span>
                </dd>
            </dl>
            <dl class="<?php echo $this->formError['lastName'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="login" type="text" name="lastName" value="<?php echo $this->lastName; ?>" />
                    <label class="pseudo-label">Last Name</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid Last Name</span>
                </dd>
            </dl>
            <dl class="<?php echo $this->formError['password'] ? 'invalid' : ''; ?>">
                <dt>
                    <input id="password" type="password" name="password" value="" />
                    <label class="pseudo-label">Password</label>
                    <span class="validation-arrow">&nbsp;</span>
                </dt>
                <dd>
                    <span class="validation">Please Enter a valid Password</span>
                </dd>
            </dl>
            <dl>
                <dt>
                    <select name="admin">
                    	<option value="1">Admin User</option>
                    	<option value="0" selected="selected">Non Admin User</option>
                    </select>
                </dt>
            </dl>
        </fieldset>
        <button class="green-button" type="submit" name="submit" value="register">
            <span>register</span>
        </button>
    </form>    
</div>