<div class="back-button-container">
    <button onclick="location.href='/disciples'" class="black-button"><span>back</span></button>
</div>
<div class="inner-right">
    <h1>Admin Options<br /><em class="alt">Managing the admin data such as the available duties, relations, marital status and users</em></h1>
    <p><b>Please select one of the options you'd like to perform...</b></p>
    
    <p><a href="/disciples/admin/duty">Managing Duty Options</a></p>      
    <p><a href="#">Managing Family Relation Options</a></p>
    <p><a href="#">Managing Marital status Options</a></p>
    <p><a href="#">Managing Users</a></p>
</div>